import machine
import time
pin0=machine.Pin(16,machine.Pin.OUT)
pin1=machine.Pin(4,machine.Pin.OUT)
pin2=machine.Pin(0,machine.Pin.OUT)
pin3=machine.Pin(14,machine.Pin.OUT)
pin4=machine.Pin(12,machine.Pin.OUT)
pin5=machine.Pin(13,machine.Pin.OUT)

for i in range(10):
    pin0.value(1)
    time.sleep(0.1)
    pin0.value(0)
    time.sleep(0.1)
    pin1.value(1)
    time.sleep(0.1)
    pin1.value(0)
    time.sleep(0.1)
    pin2.value(1)
    time.sleep(0.1)
    pin2.value(0)
    time.sleep(0.1)
    pin3.value(1)
    time.sleep(0.1)
    pin3.value(0)
    time.sleep(0.1)
    pin4.value(1)
    time.sleep(0.1)
    pin4.value(0)
    time.sleep(0.1)
    pin5.value(1)
    time.sleep(0.1)
    pin5.value(0)
